name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '5 4 * * 1'

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows']
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: |
          powershell -command "[System.Environment]::SetEnvironmentVariable('GITHUB_SCRIPT', ('{0}' -replace '\\','\\'))"
          msys2 -c 'source $GITHUB_ENV >/dev/null; export $(cut -d= -f1 $GITHUB_ENV) >/dev/null; if grep -q ErrorActionPreference $(cygpath $GITHUB_SCRIPT); then sed -i 1d $(cygpath $GITHUB_SCRIPT); sed -i \$d $(cygpath $GITHUB_SCRIPT); fi; source $(cygpath $GITHUB_SCRIPT)'
    steps:
    - name: msys2 linux compatibility
      if: matrix.os != 'windows'
      run: |
        alias powershell=:
        alias msys2=bash
    - name: Setup msys2
      if: matrix.os == 'windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
    - name: Setup paths and env
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        echo "ANT_HOME=foo" >> $GITHUB_ENV
        echo "ANT_HOME2=bar" >> $GITHUB_ENV
    - name: Run env
      run: |
        env
    - name: Grep env
      run: |
        env | grep LD_LIBRARY_PATH
    - name: Grep env
      run: |
        env | grep LD_LIBRARY_PATH | grep local
    - name: Grep env
      continue-on-error: true
      run: |
        env | grep LD_LIBRARY_PATH | grep local | grep foo
