name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '5 4 * * 1'

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows']
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: |
          powershell -command "[System.Environment]::SetEnvironmentVariable('GITHUB_SCRIPT', ('{0}' -replace '\\','\\')); dir Env:; echo WHAT IS THE SCRIPT CONTENTS; type {0}; echo THE END"
          msys2 -c 'echo ORIGINAL SCRIPT BELOW; cat $(cygpath $GITHUB_SCRIPT); echo END OF SCRIPT; if [[ -v MSYSTEM ]]; sed -i 1d $(cygpath $GITHUB_SCRIPT); sed -i \$d $(cygpath $GITHUB_SCRIPT); source $(cygpath $GITHUB_SCRIPT); fi'
    steps:
    - name: msys2 linux compatibility
      if: matrix.os != 'windows'
      run: |
        alias powershell=:
        alias msys2=bash
    - name: Setup msys2
      if: matrix.os == 'windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
    - name: Setup paths and env
      run: |
        echo "PKG_CONFIG_PATH=$HOME/.msys_ci_test_path/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/.msys_ci_test_path/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PATH=$HOME/.msys_ci_test_path/bin:$PATH" >> $GITHUB_ENV
        echo "/msys_ci_test_path/foo" >> $GITHUB_PATH
    - name: Setup one more
      run: |
        echo "FOO=BAR" >> $GITHUB_ENV
        echo "/msys_ci_test_path/hooray" >> $GITHUB_PATH
    - name: Overwrite an old one
      run: |
        echo "FOO=WHYNOT" >> $GITHUB_ENV
    - name: Run env
      run: |
        env
    - name: Check that LD_LIBRARY_PATH is modified
      run: |
        echo $LD_LIBRARY_PATH | grep msys_ci_test_path
    - name: Check that PATH is modified
      run: |
        echo $PATH | grep msys_ci_test_path
    - name: Check that PKG_CONFIG_PATH is modified
      run: |
        echo $PKG_CONFIG_PATH | grep msys_ci_test_path
    - name: Check that uname works
      run: uname -a
